version = 0.1

[default.deploy.parameters]
stack_name = "tutt-enterprises-portal"
region = "us-east-1"
profile = "denduluru"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = "AvailabilityURLTemplate='https://dgzkhduhti.execute-api.us-east-1.amazonaws.com/availability?serviceId={serviceId}'"
